### PR TITLE
Fix typo of WAMR_CONFIGUABLE_BOUNDS_CHECKS

### PR DESCRIPTION
**Pull request by wenyongh**
Change to WAMR_CONFIGURABLE_BOUNDS_CHECKS, and fix codeql compilation errors
which were introduced by PR #3406.

ps.
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3393#discussion_r1591810998
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/9055318553/job/24876266629

### CODE REVIEW

**Comment by wenyongh** [comment]
> how about .github/scripts/codeql_buildscript.sh?

Thanks, updated, and fixed CodeQL CI compilation errors in wasm loader which were introduced in PR https://github.com/bytecodealliance/wasm-micro-runtime/pull/3406.

**Review by no1wudi — APPROVED** [review]
