### ISSUE TITLE
Fail to build iwasm after #1928 merged

### ISSUE THREAD

**Issue by CSZongzi** [bytecodealliance/wasm-micro-runtime#1949]
I followed the instructions in [WASR Document - Docker Environment Preparation](https://wamr.gitbook.io/document/basics/getting-started/devcontainer). In the container, my toolchain version is as follows:

- cmake version 3.25.2
- gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
- clang version 15.0.7

When I try to build iwasm vmcore, I get this error:

``` plain
refcount.h:132:2: error: "Reference counter isn't implemented"
```

I tried reverting commit 17f3375, which temporarily fixed the issue. I don't understand why this problem occurs, can someone help me?

Full cmake log attached: [cmake.log](https://github.com/bytecodealliance/wasm-micro-runtime/files/10702665/cmake.log)

**Comment by CSZongzi** [comment]
Oh I understand why it happens. The reason for this problem is that my cmake uses clang to compile, which causes `__GNUC_PREREQ` macro to not take effect.
