### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by wenyongh**
The compilation errors were introduced by #3515 and occur in debug building
when wasm mini loader is compiled or GC is enabled.

And remove two wasm files in standalone test-running-modes case,
which will be generated by run.sh.

### CODE REVIEW

**Comment by yamt** [comment]
i guess it's worth to have a debug build on the ci.

**Review by yamt — APPROVED** [review]
