### PR TITLE
feat: Use system libuv if available

### PR DESCRIPTION
**Pull request by phated**
This is my attempt at searching for the system libuv ~~before~~ instead of downloading it, if libuv exists on the system already. As I mentioned in https://github.com/bytecodealliance/wasm-micro-runtime/issues/1831, this is needed because some tools build in a sandbox and clear the extra sources.

I didn't implement this for uvwasi because I wanted to get feedback first.

### CODE REVIEW

File: core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake [hunk 1]
```diff
@@ -8,21 +8,33 @@ set (LIBUV_VERSION v1.44.2)
 add_definitions (-DWASM_ENABLE_LIBC_WASI=1 -DWASM_ENABLE_UVWASI=1)
 
 include(FetchContent)
+include(FindPackageHandleStandardArgs)
+
+# Based on https://github.com/xenoscopic/libuv-cmake/blob/fc164590c6c723fd474e35b0b52022ebaecef745/Findlibuv.cmake
+find_path (libuv_INCLUDE_DIR NAMES uv.h)
+find_library (libuv_LIBRARY NAMES uv libuv)
+find_package_handle_standard_args(libuv libuv_LIBRARY libuv_INCLUDE_DIR)
```
Comment (lum1n0us) [inline core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: IIUC, L14 and L15 will search *uv.h* and *libuv.so* in the default path which usually is also the system path and doesn't include a directory of WAMR source tree. So I am not sure it will locate the libuv downloaded by CMake.

Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: This is not designed to load libuv downloaded by cmake. It is only downloaded below if there is no system installed libuv

Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: I've updated the original description for clarity

Comment (lum1n0us) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: Got it. It would be helpful if using system providing libuv.so. 

BTW, how about the version of system installed libuv? Should  be worried about the compatibility problem?

Comment (wenyongh) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: And how to install the system packages of libuv and uvwasi? Could you help update the document?

Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: > And how to install the system packages of libuv and uvwasi? Could you help update the document?

@wenyongh this PR is not completed. Is this a good way to proceed? If so, I can make similar changes for uvwasi.

Comment (wenyongh) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: It is good to me if it really resolves the issue that developers met, could you make the changes for uvwasi, and update the document? e.g. update the `Note` of `Configure LIBC` here:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/build_wamr.md#configure-libc

Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:16]: I've been working on this, but when the uvwasi source isn't available, the cmake build process errors that it cannot find any of the symbols. Either I'm incorrectly linking uvwasi or maybe it doesn't support linking.

**Comment by phated** [comment]
I believe this is completed but it relies on https://github.com/nodejs/uvwasi/pull/210

File: core/iwasm/libraries/libc-uvwasi/FindLIBUV.cmake [hunk 2]
```diff
@@ -0,0 +1,25 @@
+# Find libuv library
```
Comment (wenyongh) [inline core/iwasm/libraries/libc-uvwasi/FindLIBUV.cmake:1]: Should add license header, please refer to other cmake file

File: core/iwasm/libraries/wasi-nn/test/CMakeLists.txt [hunk 3]
```diff
@@ -162,12 +162,12 @@ add_executable (iwasm ${WAMR_ROOT_DIR}/product-mini/platforms/${WAMR_BUILD_PLATF
 
 install (TARGETS iwasm DESTINATION bin)
 
-target_link_libraries (iwasm vmlib ${LLVM_AVAILABLE_LIBS} ${UV_A_LIBS} ${TENSORFLOW_LIB} -lm -ldl -lpthread)
+target_link_libraries (iwasm vmlib ${LLVM_AVAILABLE_LIBS} ${UV_A_LIBS} ${UVWASI_LIBS} ${TENSORFLOW_LIB} -lm -ldl -lpthread)
```
Comment (wenyongh) [inline core/iwasm/libraries/wasi-nn/test/CMakeLists.txt:165]: Can we `set (UV_A_LIBS "${UV_A_LIBS} ${UVWASI_LIBS}")` in lib_uvwasi.cmake so that we don't need to change these cmake files?

File: core/iwasm/libraries/libc-uvwasi/FindLIBUV.cmake (hunk 2 above)
Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/FindLIBUV.cmake:4]: Done

File: core/iwasm/libraries/wasi-nn/test/CMakeLists.txt (hunk 3 above)
Comment (phated) [reply core/iwasm/libraries/wasi-nn/test/CMakeLists.txt]: Done

**Comment by phated** [comment]
Looks like some of the linux tests flaked on trying to download an image

File: core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake [hunk 4]
```diff
@@ -9,36 +9,52 @@ add_definitions (-DWASM_ENABLE_LIBC_WASI=1 -DWASM_ENABLE_UVWASI=1)
...
+        GIT_REPOSITORY https://github.com/nodejs/uvwasi.git
+        GIT_TAG main
+    )
+    FetchContent_GetProperties(uvwasi)
+    if (NOT uvwasi_POPULATED)
+        message("-- Fetching uvwasi ..")
+        FetchContent_Populate(uvwasi)
+        include_directories("${uvwasi_SOURCE_DIR}/include")
+        add_subdirectory(${uvwasi_SOURCE_DIR} ${uvwasi_BINARY_DIR} EXCLUDE_FROM_ALL)
+        set (UVWASI_LIBRARIES uvwasi_a)
```
[the remark this answers is not in the document]
Comment (wenyongh) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: typo: add them

[the remark this answers is not in the document]
Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: It looks like this was already added for uv_a so I just added it to `uvwasi_a`

[the remark this answers is not in the document]
Comment (wenyongh) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: The issue in my machine is that package libuv1-dev is installed while no uvwasi related package is installed, and `find_package(LIBUV QUIET)` returns true but uvwasi must be compiled from source code. And when downloading and compiling uvwasi, `it also downloads, compiles and links libuv (static lib)` instead of linking the libuv.so from the installed package. And here the compiler reports error when linking libuv.a. I don't know how to let uvwasi use the installed libuv package directly, if we can, it is unnecessary to add the line. Otherwise, had better add the line. Any idea for it? Thanks.

[the remark this answers is not in the document]
Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: >  I don't know how to let uvwasi use the installed libuv package directly, if we can, it is unnecessary to add the line.

Sorry for the confusion. My PR at https://github.com/nodejs/uvwasi/pull/210 was required to have uvwasi use the same global version. I've now merged the PR into the main branch so you should be able to build with the new source code and it will link the global libuv.

[the remark this answers is not in the document]
Comment (wenyongh) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: OK, thanks a lot. I tested again, it links the correct libuv now. An issue is in Ubuntu-20.04, when package libuv1-dev is installed, compile warning and link error occur:
```bash
product-mini/platforms/linux/build/_deps/uvwasi-src/src/uvwasi.c:1743:7: warning: implicit declaration of function ‘uv_fs_lutime’; did you mean ‘uv_fs_futime’? [-Wimplicit-function-declaration]
 1743 |   r = uv_fs_lutime(NULL, &req, resolved_path, atim, mtim, NULL);
```
```bash
[ 98%] Linking C executable iwasm
/usr/local/bin/ld: _deps/uvwasi-build/libuvwasi_a.a(uvwasi.c.o): in function `uvwasi_path_filestat_set_times':
uvwasi.c:(.text+0x293f): undefined reference to `uv_fs_lutime'
```
Note that the warning/error isn't reported in Ubuntu-22.04, it works fine in Ubuntu-22.04.
I think it is due to the installed libuv.so doesn't have the `uv_fs_lutime` function. It is not the issue of this PR, let's merge it first. And it would be good if we can resolve the issue, e.g. modifying uvwasi by using `uv_fs_futime`?

[the remark this answers is not in the document]
Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: That sounds good. I don't have experience with the libuv function mentioned, but I can raise the issue for the other members of the uvwasi team with more libuv experience.

[the remark this answers is not in the document]
Comment (phated) [reply core/iwasm/libraries/libc-uvwasi/libc_uvwasi.cmake:52]: That issue has been raised at https://github.com/nodejs/uvwasi/issues/213
