### ISSUE TITLE
Nightly run failed when building iwasm with gcc-4.8

### ISSUE THREAD

**Issue by wenyongh** [bytecodealliance/wasm-micro-runtime#2552]
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/6192148810/job/16811719305
```
In file included from /__w/wasm-micro-runtime/wasm-micro-runtime/product-mini/platforms/linux/main.c:6:0:
/__w/wasm-micro-runtime/wasm-micro-runtime/product-mini/platforms/linux/../posix/main.c:500:5: error: expected specifier-qualifier-list before '_Atomic'
     _Atomic bool cancel;
```

The issue is introduced with PR #2538, seems that `_Atomic` isn't supported by gcc-4.8.
@yamt Could you help look into it?

**Comment by yamt** [comment]
i will take a look.
