### ISSUE TITLE
Zephyr build broken after PR #2740

### ISSUE THREAD

**Issue by hasheddan** [bytecodealliance/wasm-micro-runtime#2760]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/2740 breaks the Zephyr build with the following errors:

```
In file included from /home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/../platform/include/platform_common.h:13,
                 from /home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/bh_platform.h:9,
                 from /home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/iwasm/common/wasm_runtime_common.h:9,
                 from /home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/iwasm/common/wasm_memory.c:6:
/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/platform/zephyr/platform_internal.h:152:9: error: unknown type name 'DIR'
  152 | typedef DIR *os_dir_stream;
      |         ^~~
In file included from /home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/bh_platform.h:11:
/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/../platform/include/platform_api_extension.h:250:16: error: unknown type name 'korp_rwlock'
  250 | os_rwlock_init(korp_rwlock *lock);
      |                ^~~~~~~~~~~
/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/../platform/include/platform_api_extension.h:260:18: error: unknown type name 'korp_rwlock'
  260 | os_rwlock_rdlock(korp_rwlock *lock);
      |                  ^~~~~~~~~~~
/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/../platform/include/platform_api_extension.h:270:18: error: unknown type name 'korp_rwlock'
  270 | os_rwlock_wrlock(korp_rwlock *lock);
      |                  ^~~~~~~~~~~
/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/../platform/include/platform_api_extension.h:280:18: error: unknown type name 'korp_rwlock'
  280 | os_rwlock_unlock(korp_rwlock *lock);
      |                  ^~~~~~~~~~~
/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/utils/../platform/include/platform_api_extension.h:290:19: error: unknown type name 'korp_rwlock'
  290 | os_rwlock_destroy(korp_rwlock *lock);
      |                   ^~~~~~~~~~~
[27/442] Building C object CMakeFiles/app.dir/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/mem-alloc/ems/ems_hmu.c.obj
FAILED: CMakeFiles/app.dir/home/hasheddan/code/github.com/bytecodealliance/wasm-micro-runtime/core/shared/mem-alloc/ems/ems_hmu.c.obj 
```

I am working on a fix here and will open a PR ASAP :)

**Comment by hasheddan** [comment]
Confirmed build works as expected at https://github.com/bytecodealliance/wasm-micro-runtime/commit/314ecba388fe70e4da20b14b6b740b9290078173

**Comment by hasheddan** [comment]
This has been fixed by #2777 -- thanks @wenyongh!
