### ISSUE TITLE
zephyr: old versions support

### ISSUE THREAD

**Issue by mkolchurin** [bytecodealliance/wasm-micro-runtime#3178]
Do we need support for ancient versions of Zephyr that were released more than 5-6 years ago (`/* version 1.14.1 */`)? It might be much better to focus on newer versions (at least 2.7.0 LTS release, best 3.3.0)

[End-of-life releases](https://docs.zephyrproject.org/latest/releases/eol_releases.html)

The problem is that I'm trying to add new functionality (for example, support for `Alloc_With_System_Allocator` instead of `Alloc_With_Pool`), and it's hard to keep track of what has changed after so many releases.

**Comment by wenyongh** [comment]
@mkolchurin it is really hard to support these ancient zephyr versions, I believe that they are rarely used by zephyr developers now, maybe we just don't add the version control in your Alloc_With_System_Allocator PR, and fix it when others report compilation error.

**Comment by srberard** [comment]
I would say that it's not worth supporting directly.  According to the Zephyr project 1.14.x is no longer supported.  Here's the supported release table from Zephyr:
![image](https://github.com/bytecodealliance/wasm-micro-runtime/assets/581348/bfba3e02-4fb4-415f-8243-535b2401b525)

I'd rather see effort going to properly support the current releases of Zephyr.  There's a number of issues that are not working on Zephyr 3.5/3.6.
